### ISSUE TITLE
 Codes in different categories

### ISSUE THREAD

**Issue by ChoEunHyeon** [AFei19911012/WPFSamples#2]
Could you also share the code for the other items in the image? I can't find example in the project
like 2-2, 2-3, 2-4, ...

![image](https://user-images.githubusercontent.com/24432573/209829451-25caa61a-8cb4-49c7-9a18-aaa978503e95.png)

**Comment by AFei19911012** [comment]
邮件已收到。

**Comment by ChoEunHyeon** [comment]
igbtkj@gmail.com

I want to use it for study.
I am also willing to pay for it.

**Comment by AuburnXu** [comment]
此异常最初是在此调用堆栈中引发的: 
    HalconDotNet.HHandle.HHandle()
    HalconDotNet.HHandleBase.HHandleBase()

内部异常 1:
DllNotFoundException: 无法加载 DLL“halcon”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

**Comment by AFei19911012** [comment]
邮件已收到。

**Comment by AFei19911012** [comment]
安装 Halcon，配置好环境，引用 halcondotnet.dll

**Comment by AuburnXu** [comment]
＋V：DFG9208  有偿求助

**Comment by AuburnXu** [comment]
＋V：DFG9208
I want to use it for study.
I am also willing to pay for it.

**Comment by AFei19911012** [comment]
所有的视觉测试项目已上传，自行学习
